#!/usr/bin/env python3
"""Generate a C header containing the Beacon RSA public key from a hex file."""

from __future__ import annotations

import argparse
import pathlib
import sys

def hex_to_c_string(hex_string: str) -> str:
    # Strip all whitespace
    hex_data = "".join(hex_string.split())
    # Convert hex pairs to \xHH
    return ''.join(f'\\x{hex_data[i:i+2]}' for i in range(0, len(hex_data), 2))

def generate_header(input_path: pathlib.Path, output_path: pathlib.Path) -> int:
    if not input_path.exists():
        print(f"ERROR: Input public key file not found: {input_path}")
        return 1

    hex_data = input_path.read_text(encoding="utf-8").strip()
    if not hex_data:
        print(f"ERROR: Public key file is empty: {input_path}")
        return 1

    c_string = hex_to_c_string(hex_data)
    
    header_content = [
        "#ifndef PUBLIC_KEY_H",
        "#define PUBLIC_KEY_H",
        "",
        "/* Generated by generate-payload/GeneratePublicKeyHeader.py */",
        f'unsigned char BEACON_PUBLIC_KEY[256] = "{c_string}";',
        "unsigned int BEACON_PUBLIC_KEY_LEN = 256;",
        "",
        "#endif /* PUBLIC_KEY_H */",
        ""
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(header_content), encoding="utf-8")
    
    print(f"WROTE {output_path}")
    return 0

def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate public_key.h from publickey.txt")
    parser.add_argument("input", type=pathlib.Path, help="Path to hex public key file")
    parser.add_argument("output", type=pathlib.Path, help="Path to generated header output")
    return parser.parse_args(argv)

def main(argv: list[str]) -> int:
    args = parse_args(argv)
    try:
        return generate_header(args.input, args.output)
    except Exception as exc:
        print(f"ERROR GeneratePublicKeyHeader: {exc}")
        return 1

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
